# Generated by Django 5.2.15 on 2026-06-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('status', models.CharField(default='Inventory', max_length=50, verbose_name='Status')),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Name')),
                ('vendor_invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('vendor_invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('vendor_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vendor Amount')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('work_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Work Order')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
